frase=input("Escribe una frase: ")
palabras_separadas=frase.split(" ")
cantidad_de_palabras= len(palabras_separadas)
print(f"Dijiste {cantidad_de_palabras} palabras, y tardarías {cantidad_de_palabras/2} segundos en decirlo")
print(f"Dalto lo diría en {round((cantidad_de_palabras/2)/1.30,2)}")